name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # specify your required Python version

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # specify your required Python version

    - name: Build with Bazel
      run: |
        sudo apt-get update
        sudo apt-get install -y python3
        python3 --version
        bazel build //:main
        ./bazel-bin/main
